name: jukebox
channels:
  - conda-forge
  - pytorch
  - bricew
dependencies:
  - python=3.8
  - mpi4py=3.0.3
  - fire==0.1.3
  - tqdm==4.45.0
  - soundfile==0.10.2
  - unidecode==1.1.1
  - librosa==0.7.2
  - numba==0.48.0
  - ipython=7.18.1
  - pytorch=1.6.0
  - torchvision=0.7
  - cudatoolkit=10.2
  - fastapi=0.61.1
  - uvicorn=0.12.2
  - pydantic=1.7.2
